POST http://localhost:5000/api/v1/companies/auth
Content-Type: application/json

###

GET http://localhost:5000/posts

###
POST http://localhost:5000/posts
Content-Type: application/json

{
    "title": "Post 1",
    "content": "Content 1"
}

###

GET http://localhost:5000/api/v1/applications

###

POST http://localhost:5000/api/v1/applications
Content-Type: application/json


{
    "name": "sonkey",
    "email": "sonkey@email.com",
   

}
